language: haskell

env:
  - GHCVER=7.6.3
  - GHCVER=7.8.2
  - GHCVER=head

matrix:
  allow_failures:
    - env: GHCVER=head

before_install:
  - |
    # Install the GHC we want from hvr's PPA
    sudo add-apt-repository -y ppa:hvr/ghc
    sudo apt-get update
    sudo apt-get install ghc-$GHCVER cabal-install-1.18
    export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/1.18/bin:$PATH
    # Install recent alex and happy that work with GHC 7.8 and head
    sudo apt-get install alex-3.1.3 happy-1.19.3
    export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.3/bin:$PATH
  - ghc --version
  - cabal --version
  - alex --version
  - happy --version

install:
  - cabal update
  - cabal install --dependencies-only --enable-tests

script:
  - cabal configure --enable-tests
  - cabal build
  - cabal test --show-details=always

notifications:
  irc:
    channels:
      - "irc.freenode.org#haskell-lens"
    skip_join: true
    template:
      - "\x0313succinct\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
